spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
management:
  endpoint:
    health:
      enabled: true
---

spring.profiles: prod
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
  rabbitmq:
    host: rabbit
